apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ingress-route.yaml

patches:
- path: config-map.yaml
- path: deployment.yaml
images:
- digest: sha256:9f3821ce278769658c165b92b86868f752d5e79f89ca90fbdf8106e9bcc7f8f0
  name: us-central1-docker.pkg.dev/beaming-night-424319-g5/playground/local-gpt:prod
  newName: us-central1-docker.pkg.dev/beaming-night-424319-g5/playground/local-gpt
