apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: playground
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app
      app.kubernetes.io/part-of: playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app
        app.kubernetes.io/part-of: playground
    spec:
      containers:
        - name: app
          image: us-central1-docker.pkg.dev/beaming-night-424319-g5/playground/web
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: web-config-map
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              #cpu: 500m
              memory: 256Mi
